### ISSUE TITLE
Backdoor to https://www.tahribat.com/svrcommand?cmd=trp&p=

### ISSUE THREAD

**Issue by ItsPaPPy** [HolyOne/C99Shell-PHP8#1]
https://github.com/HolyOne/C99Shell-PHP8/blob/05f098d1361021eb12ef49be446a6fc9f8384b2e/c99.php#L99
https://github.com/HolyOne/C99Shell-PHP8/blob/05f098d1361021eb12ef49be446a6fc9f8384b2e/c99.php#L100
https://github.com/HolyOne/C99Shell-PHP8/blob/05f098d1361021eb12ef49be446a6fc9f8384b2e/c99.php#L5067

Creator added a backdoor to log every instance of this to their site, so they can also use it.

**Comment by HolyOne** [comment]
It is not a bug, its a feature

**Comment by HolyOne** [comment]
I will keep it here so anyone can delete the lines or configure that to their own server
